/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles.usuarios.resources;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.usuario;
import paneles.usuarios.ViewCreateUser;

/**
 *
 * @author isacc-PC
 */
public class ListUsers extends javax.swing.JPanel {

    private int userSelect = 0;

    /**
     * Creates new form ListUsers
     */
    public ListUsers() {
        initComponents();

        usuario_model = new usuario();

        cargarTablaDeUsuarios();
    }

    public void cargarTablaDeUsuarios() {

        usuarios = usuario_model.getAllUsers();

        String[] columnNames = usuarios.get(0);

        List<String[]> dataList = usuarios.subList(1, usuarios.size());

        Object[][] data = new Object[dataList.size()][columnNames.length];

        for (int i = 0; i < dataList.size(); i++) {
            data[i] = dataList.get(i);
        }

        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bt_create_user = new resources.ButtonGradient();
        title_page = new javax.swing.JLabel();
        bt_refresh = new resources.ButtonGradient();
        bt_delete_user = new resources.ButtonGradient();

        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bt_create_user.setText("Nuevo Usuario");
        bt_create_user.setColor1(new java.awt.Color(0, 204, 0));
        bt_create_user.setColor2(new java.awt.Color(0, 153, 51));
        bt_create_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_create_userActionPerformed(evt);
            }
        });

        title_page.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        title_page.setText("Lista de usuarios");

        bt_refresh.setText("Recargar");
        bt_refresh.setColor1(new java.awt.Color(153, 153, 153));
        bt_refresh.setColor2(new java.awt.Color(153, 153, 153));
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        bt_delete_user.setText("Eliminar Usuario Seleccionado");
        bt_delete_user.setColor1(new java.awt.Color(255, 51, 51));
        bt_delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_delete_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title_page, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(title_page)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_create_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_create_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_create_userActionPerformed
        if (listener != null) {
            listener.showView();
        }
    }//GEN-LAST:event_bt_create_userActionPerformed

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        cargarTablaDeUsuarios();
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int fila = jTable1.getSelectedRow();
        int columna = jTable1.getSelectedColumn();

        if (fila != -1 && columna != -1) {
            Object idObject = jTable1.getModel().getValueAt(fila, 0);

            String idString = idObject.toString();

            userSelect = Integer.parseInt(idString);
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void bt_delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_delete_userActionPerformed
        int rs = JOptionPane.showConfirmDialog(this, "¿Estas seguro que quieres eliminar a este usuario?");
        
        if (rs != JOptionPane.YES_OPTION) {
            return;
        }

        usuario_model.deleteUser(userSelect);
        
        JOptionPane.showMessageDialog(this, "Usuario eliminado");
    }//GEN-LAST:event_bt_delete_userActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.ButtonGradient bt_create_user;
    private resources.ButtonGradient bt_delete_user;
    private resources.ButtonGradient bt_refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel title_page;
    // End of variables declaration//GEN-END:variables

    private usuario usuario_model;
    private ViewCreateUser listener;
    private List<String[]> usuarios;

    public void setShowCreateUser(ViewCreateUser listener) {
        this.listener = listener;
    }
}
