/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles.usuarios.resources;

import control.cargar_combx;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.usuario;
import models.validar_campos;

/**
 *
 * @author isacc-PC
 */
public class NewUser extends javax.swing.JPanel {

    cargar_combx carga = new cargar_combx();
    int idrol = -1;

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();

        carga.consul_usuario(ip_role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ip_role = new resources.ComboboxSuggestion.ComboBoxSuggestion();
        lb_type_user = new javax.swing.JLabel();
        ip_name = new javax.swing.JTextField();
        lb_idcard = new javax.swing.JLabel();
        lb_name = new javax.swing.JLabel();
        ip_idcard = new javax.swing.JTextField();
        ip_password = new javax.swing.JPasswordField();
        lb_password = new javax.swing.JLabel();
        ip_password_repet = new javax.swing.JPasswordField();
        lb_password_repet = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_comida_favorita = new javax.swing.JLabel();
        ip_comida_favorita = new javax.swing.JTextField();
        ip_animal_favorito = new javax.swing.JTextField();
        lb_animal_favorito = new javax.swing.JLabel();
        lb_color_favorito = new javax.swing.JLabel();
        ip_color_favorito = new javax.swing.JTextField();
        lb_comida_favorita_error = new javax.swing.JLabel();
        lb_animal_favorito_error = new javax.swing.JLabel();
        lb_color_favorito_error = new javax.swing.JLabel();
        bt_save_from = new resources.ButtonGradient();
        bt_clean_from = new resources.ButtonGradient();
        jLabel1 = new javax.swing.JLabel();
        ojo_usua = new javax.swing.JLabel();
        lb_type_user_error = new javax.swing.JLabel();
        lb_idcard_error = new javax.swing.JLabel();
        lb_name_error = new javax.swing.JLabel();
        lb_password_error = new javax.swing.JLabel();
        lb_password_repet_error = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 500));

        ip_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_roleActionPerformed(evt);
            }
        });

        lb_type_user.setText("Tipo de usuario");

        ip_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));
        ip_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_nameActionPerformed(evt);
            }
        });

        lb_idcard.setText("Cedula de identidad");

        lb_name.setText("Nombre");

        ip_idcard.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));
        ip_idcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip_idcardKeyTyped(evt);
            }
        });

        ip_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));
        ip_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_passwordActionPerformed(evt);
            }
        });
        ip_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip_passwordKeyTyped(evt);
            }
        });

        lb_password.setText("Contraseña");

        ip_password_repet.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));
        ip_password_repet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ip_password_repetActionPerformed(evt);
            }
        });
        ip_password_repet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ip_password_repetKeyTyped(evt);
            }
        });

        lb_password_repet.setText("Repetir Contrasena");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preguntas de Seguridad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        lb_comida_favorita.setText("Comida Favorita");

        ip_comida_favorita.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));

        ip_animal_favorito.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));

        lb_animal_favorito.setText("Animal Favorito");

        lb_color_favorito.setText("Color Favorito");

        ip_color_favorito.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(68, 136, 238)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ip_color_favorito, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(ip_animal_favorito)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_animal_favorito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_animal_favorito_error))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_color_favorito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_color_favorito_error)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_comida_favorita_error)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ip_comida_favorita, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_comida_favorita)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lb_comida_favorita_error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_animal_favorito)
                    .addComponent(lb_animal_favorito_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ip_animal_favorito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_color_favorito)
                    .addComponent(lb_color_favorito_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ip_color_favorito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(lb_comida_favorita)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ip_comida_favorita, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );

        bt_save_from.setText("Guardar");
        bt_save_from.setColor1(new java.awt.Color(0, 204, 0));
        bt_save_from.setColor2(new java.awt.Color(0, 204, 102));
        bt_save_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_save_fromActionPerformed(evt);
            }
        });

        bt_clean_from.setText("Limpiar");
        bt_clean_from.setColor1(new java.awt.Color(153, 153, 153));
        bt_clean_from.setColor2(new java.awt.Color(153, 153, 153));
        bt_clean_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clean_fromActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Crear Usuario");

        ojo_usua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojo_usuaMouseClicked(evt);
            }
        });
        ojo_usua.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ip_idcard)
                        .addComponent(ip_role, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_password)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_password_error))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_type_user)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lb_type_user_error))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lb_name)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_name_error)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_password_repet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_password_repet_error))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_idcard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_idcard_error))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ip_password_repet, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ip_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(ip_name, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ojo_usua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_clean_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bt_save_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_type_user)
                    .addComponent(lb_type_user_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_save_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_clean_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ip_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_idcard)
                            .addComponent(lb_idcard_error))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ip_idcard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_name)
                            .addComponent(lb_name_error))
                        .addGap(11, 11, 11)
                        .addComponent(ip_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_password)
                            .addComponent(lb_password_error))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ip_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_password_repet)
                            .addComponent(lb_password_repet_error))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ip_password_repet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ojo_usua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ip_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_nameActionPerformed

    private void ip_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip_passwordKeyTyped
        ip_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (ip_password.getText().length() >= 20) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_ip_passwordKeyTyped

    private void ip_password_repetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip_password_repetKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_password_repetKeyTyped

    private void ip_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_passwordActionPerformed

    private void bt_clean_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clean_fromActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_bt_clean_fromActionPerformed

    private void ojo_usuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo_usuaMouseClicked
        // TODO add your handling code here:
        if (ip_password.getEchoChar() == (char) 0 || ip_password_repet.getEchoChar() == (char) 0) {
            ip_password.setEchoChar('*');
            ip_password_repet.setEchoChar('*');
            ojo_usua.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png")));
        } else {
            ip_password.setEchoChar((char) 0);
            ip_password_repet.setEchoChar((char) 0);
            ojo_usua.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_abierto.png")));
        }
    }//GEN-LAST:event_ojo_usuaMouseClicked

    private void ip_password_repetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_password_repetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ip_password_repetActionPerformed

    private void bt_save_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_save_fromActionPerformed
        storeUser();
    }//GEN-LAST:event_bt_save_fromActionPerformed

    private void ip_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ip_roleActionPerformed
        Object usuaseleccionado = ip_role.getSelectedItem();
        if (usuaseleccionado instanceof String) {
            String rol = (String) usuaseleccionado;
        } else if (usuaseleccionado instanceof models.rol) {
            models.rol selectedrol = (models.rol) usuaseleccionado;
            idrol = selectedrol.getId();
        }
    }//GEN-LAST:event_ip_roleActionPerformed

    private void ip_idcardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ip_idcardKeyTyped
        ip_idcard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (ip_idcard.getText().length() >= 8) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_ip_idcardKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.ButtonGradient bt_clean_from;
    private resources.ButtonGradient bt_save_from;
    private javax.swing.JTextField ip_animal_favorito;
    private javax.swing.JTextField ip_color_favorito;
    private javax.swing.JTextField ip_comida_favorita;
    private javax.swing.JTextField ip_idcard;
    private javax.swing.JTextField ip_name;
    private javax.swing.JPasswordField ip_password;
    private javax.swing.JPasswordField ip_password_repet;
    private resources.ComboboxSuggestion.ComboBoxSuggestion ip_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_animal_favorito;
    private javax.swing.JLabel lb_animal_favorito_error;
    private javax.swing.JLabel lb_color_favorito;
    private javax.swing.JLabel lb_color_favorito_error;
    private javax.swing.JLabel lb_comida_favorita;
    private javax.swing.JLabel lb_comida_favorita_error;
    private javax.swing.JLabel lb_idcard;
    private javax.swing.JLabel lb_idcard_error;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_name_error;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_password_error;
    private javax.swing.JLabel lb_password_repet;
    private javax.swing.JLabel lb_password_repet_error;
    private javax.swing.JLabel lb_type_user;
    private javax.swing.JLabel lb_type_user_error;
    private javax.swing.JLabel ojo_usua;
    // End of variables declaration//GEN-END:variables

    private void storeUser() {
        if (ip_idcard.getText().trim().isEmpty()
                || ip_name.getText().trim().isEmpty()
                || ip_password.getText().trim().isEmpty()
                || ip_password_repet.getText().trim().isEmpty()
                || ip_animal_favorito.getText().trim().isEmpty()
                || ip_color_favorito.getText().trim().isEmpty()
                || ip_comida_favorita.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Campos Vacíos");
            validar_campos.validarCampoVacio(ip_idcard, lb_idcard_error);
            validar_campos.validarCampoVacio(ip_name, lb_name_error);
            validar_campos.validarCampoVacio(ip_password, lb_password_error);
            validar_campos.validarCampoVacio(ip_password_repet, lb_password_repet_error);
            validar_campos.validarCampoVacio(ip_comida_favorita, lb_comida_favorita_error);
            validar_campos.validarCampoVacio(ip_animal_favorito, lb_animal_favorito_error);
            validar_campos.validarCampoVacio(ip_color_favorito, lb_color_favorito_error);

            return;
        }

        boolean valido = validar_campos.validarPasswords(ip_password, ip_password_repet, lb_password_error, lb_password_error);

        if (!valido) {
            return;
        }

        int cedula = Integer.parseInt(ip_idcard.getText());
        String nombre = ip_name.getText();
        String contrasena = new String(ip_password.getPassword());
        String confi_contra = new String(ip_password_repet.getPassword());
        String comida = ip_comida_favorita.getText();
        String animal = ip_animal_favorito.getText();
        String color = ip_color_favorito.getText();

        int preguard = JOptionPane.showConfirmDialog(this, "¿Desea Guardar el Usuario?");
        if (preguard == JOptionPane.YES_OPTION) {
            usuario usu = new usuario();
            usu.setCedula(cedula);
            usu.setNombre(nombre);
            usu.setPassword(contrasena);
            usu.setConfi_password(confi_contra);
            usu.setComida_favorita(comida);
            usu.setAnimal_favorito(animal);
            usu.setColor_favorito(color);
            usu.setId_rol(idrol);
            usu.save();

            JOptionPane.showMessageDialog(this, "Los Datos se Guardaron Correctamente");

            limpiarCampos();
        } else {
            limpiarCampos();
        }
    }

    public void limpiarCampos() {
        ip_role.setSelectedIndex(0);
        ip_idcard.setText("");
        ip_name.setText("");
        ip_password.setText("");
        ip_password_repet.setText("");
        ip_animal_favorito.setText("");
        ip_color_favorito.setText("");
        ip_comida_favorita.setText("");

        ip_name.requestFocusInWindow();
    }
}
