/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles.usuarios;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.usuario;
import paneles.usuarios.resources.ListUsers;
import paneles.usuarios.resources.NewUser;

/**
 *
 * @author isacc-PC
 */
public class Users extends javax.swing.JFrame implements ViewCreateUser {

    @Override
    public void showView() {
        pn_initial.removeAll();
        pn_initial.add(ViewCreateUser, BorderLayout.CENTER);
        pn_initial.revalidate();
        pn_initial.repaint();
    }

    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
        
        ViewListUsers = new ListUsers();
        ViewCreateUser = new NewUser();
        
        pn_initial.removeAll();
        pn_initial.add(ViewListUsers, BorderLayout.CENTER);
        pn_initial.revalidate();
        pn_initial.repaint();

        ViewListUsers.setShowCreateUser(this);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listUsers2 = new paneles.usuarios.resources.ListUsers();
        pn_initial = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.CardLayout());

        pn_initial.setLayout(new java.awt.CardLayout());
        getContentPane().add(pn_initial, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private paneles.usuarios.resources.ListUsers listUsers2;
    private javax.swing.JPanel pn_initial;
    // End of variables declaration//GEN-END:variables
    private NewUser ViewCreateUser;
    private ListUsers ViewListUsers;
}
