/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import models.usuario;
import models.validar_campos;
/**
 *
 * @author User
 */
public class cambio_contra extends javax.swing.JFrame {
   private int dato ;
   
    /**
     * Creates new form NewJFrame
     */
    public cambio_contra(int numero) {
        initComponents();
        ojo_cambia.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png")));
         this.dato = numero;
    }

    private cambio_contra() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cambio_contra = new fondo();
        jLabel1 = new javax.swing.JLabel();
        cancel2 = new javax.swing.JPanel();
        jButton_cancel2 = new javax.swing.JButton();
        confir2 = new javax.swing.JPanel();
        jButton_confir2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_1contra = new javax.swing.JLabel();
        jLabel_2contra = new javax.swing.JLabel();
        renovando = new javax.swing.JPasswordField();
        renovando_confi = new javax.swing.JPasswordField();
        ojo_cambia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(490, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 430));
        jPanel1.setLayout(new java.awt.CardLayout());

        cambio_contra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambiar Contraseña");
        cambio_contra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 60));

        cancel2.setBackground(new java.awt.Color(0, 204, 204));
        cancel2.setLayout(new java.awt.CardLayout());

        jButton_cancel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_cancel2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancel2.setText("Cancelar");
        jButton_cancel2.setContentAreaFilled(false);
        jButton_cancel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_cancel2MouseClicked(evt);
            }
        });
        jButton_cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancel2ActionPerformed(evt);
            }
        });
        cancel2.add(jButton_cancel2, "card2");

        cambio_contra.add(cancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 100, 30));

        confir2.setBackground(new java.awt.Color(0, 204, 204));
        confir2.setLayout(new java.awt.CardLayout());

        jButton_confir2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_confir2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_confir2.setText("Confimar");
        jButton_confir2.setContentAreaFilled(false);
        jButton_confir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confir2ActionPerformed(evt);
            }
        });
        confir2.add(jButton_confir2, "card2");

        cambio_contra.add(confir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 100, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirma contraseña:");
        jPanel5.add(jLabel5);

        cambio_contra.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 160, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        jPanel6.add(jLabel4);

        cambio_contra.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 100, 30));
        cambio_contra.add(jLabel_1contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 210, 20));
        cambio_contra.add(jLabel_2contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 20));

        renovando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                renovandoKeyTyped(evt);
            }
        });
        cambio_contra.add(renovando, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 30));

        renovando_confi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                renovando_confiKeyTyped(evt);
            }
        });
        cambio_contra.add(renovando_confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 130, 30));

        ojo_cambia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojo_cambiaMouseClicked(evt);
            }
        });
        cambio_contra.add(ojo_cambia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 40, 30));

        jPanel1.add(cambio_contra, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cancel2MouseClicked

        reset_contraseña rs = new reset_contraseña();
        rs.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton_cancel2MouseClicked

    private void jButton_cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancel2ActionPerformed

    }//GEN-LAST:event_jButton_cancel2ActionPerformed

    private void jButton_confir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confir2ActionPerformed
          boolean valido = validar_campos.validarPasswords(
            renovando, renovando_confi, jLabel_1contra, jLabel_2contra);

    if (valido) {
        String reno = new String(renovando.getPassword());
        String confir = new String(renovando_confi.getPassword());

        if (reno.equals(confir)) {
            usuario us = new usuario();
            us.setCedula(dato);  
            us.setPassword(reno);
            us.setConfi_password(confir);
            us.update();

            JOptionPane.showMessageDialog(this, "Contraseña Actualizada");

            renovando.setText("");
            renovando_confi.setText("");

            RVsistemas pm = new RVsistemas();
            pm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
        }
    }
        
     
    }//GEN-LAST:event_jButton_confir2ActionPerformed

    private void cc_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc_confActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cc_confActionPerformed

    private void renovandoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_renovandoKeyTyped
        renovando.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (renovando.getText().length() >= 20) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_renovandoKeyTyped

    private void renovando_confiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_renovando_confiKeyTyped
        renovando_confi.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (renovando_confi.getText().length() >= 20) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_renovando_confiKeyTyped

    private void ojo_cambiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo_cambiaMouseClicked
        // TODO add your handling code here:
          if (renovando.getEchoChar() == (char) 0|| renovando_confi.getEchoChar()== (char) 0) {
        renovando.setEchoChar('*'); 
        renovando_confi.setEchoChar('*'); 
        ojo_cambia.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png"))); 
    } else {
        renovando.setEchoChar((char) 0); 
        renovando_confi.setEchoChar((char) 0);
        ojo_cambia.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_abierto.png"))); 
    }
    }//GEN-LAST:event_ojo_cambiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        try {
        UIManager.setLookAndFeel(new FlatDarculaLaf()); // primero el Look&Feel
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambio_contra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cambio_contra;
    public javax.swing.JPanel cancel2;
    public javax.swing.JPanel confir2;
    public javax.swing.JButton jButton_cancel2;
    public javax.swing.JButton jButton_confir2;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel_1contra;
    javax.swing.JLabel jLabel_2contra;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel5;
    javax.swing.JPanel jPanel6;
    javax.swing.JLabel ojo_cambia;
    javax.swing.JPasswordField renovando;
    javax.swing.JPasswordField renovando_confi;
    // End of variables declaration//GEN-END:variables
class fondo extends JPanel {

     Image imag;
    
    @Override
    public void paint(Graphics g){
    
        
        imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();
        
        g.drawImage(imag,0,0,getWidth(),getHeight(),this );
        
        setOpaque(false);
        
        super.paint(g);
    }
    
}
}
