/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.sun.source.tree.BreakTree;
import common.conexion;
import control.Controller1;
import control.cargar_combx;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.animal;
import models.color;
import models.raza;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.*;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Date;
import models.validar_campos;
import models.ve_registro;

/**
 *
 * @author User
 */
public class Operation extends javax.swing.JPanel {

    cargar_combx carga = new cargar_combx();
    int idraza = 0, idsexo = 0, idpelaje = 0, idcolor = 0, idregis = 0;
    int razaid = 0, sexoid = 0, colorid = 0, pelejeid = 0;
    private JFormattedTextField fechaFormateada;
    private int idVacaActual;
    private int idAnimalInterno = 0;
    private models.animal animalEncontrado = null;
    private int razai;
    private int sexoi;
    private int colori;
    private int pelejei;

    public Controller1 controller;

    /**
     * Creates new form RClin
     */

    public Operation() {
        initComponents();
        controller = new Controller1(this);
        carga.consul_sexo(sexo_vc);
        carga.consul_pelaje(pelaje_vc);
        carga.consul_raz(raza_vc);
        carga.consul_color(color_vc);
        validar_campos.soloNumeros(id_padre, jLabel_2clint);
        validar_campos.soloNumeros(peso_vc, jLabel_5clint);
        validar_campos.soloLetras(nombre_vc, jLabel_4clint);
        validar_campos.soloNumeros(id_vc, jLabel_2clint);
        validar_campos.soloNumeros(id_madre, jLabel_6clint2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo();
        tex_buscRC = new javax.swing.JTextField();
        id_padre = new javax.swing.JTextField();
        nombre_vc = new javax.swing.JTextField();
        peso_vc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cr_lim = new javax.swing.JPanel();
        eliminar_vc = new javax.swing.JButton();
        rc_mod = new javax.swing.JPanel();
        modi_vc = new javax.swing.JButton();
        rc_guar = new javax.swing.JPanel();
        guar_vc = new javax.swing.JButton();
        sexo_vc = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_1clint = new javax.swing.JLabel();
        jLabel_2clint = new javax.swing.JLabel();
        jLabel_3clint = new javax.swing.JLabel();
        jLabel_4clint = new javax.swing.JLabel();
        jLabel_5clint = new javax.swing.JLabel();
        jLabel_6clint = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        id_vc = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        id_madre = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pelaje_vc = new javax.swing.JComboBox<>();
        color_vc = new javax.swing.JComboBox<>();
        rc_guar1 = new javax.swing.JPanel();
        limpia_vc = new javax.swing.JButton();
        raza_vc = new javax.swing.JComboBox<>();
        jLabel_6clint1 = new javax.swing.JLabel();
        jLabel_6clint2 = new javax.swing.JLabel();
        jLabel_6clint3 = new javax.swing.JLabel();
        jLabel_6clint4 = new javax.swing.JLabel();
        jLabel_6clint5 = new javax.swing.JLabel();
        rc_guar2 = new javax.swing.JPanel();
        detalles_vc = new javax.swing.JButton();
        fecha_vca = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tex_buscRC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tex_buscRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tex_buscRCActionPerformed(evt);
            }
        });
        jPanel1.add(tex_buscRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 160, 30));

        id_padre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_padre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_padreKeyTyped(evt);
            }
        });
        jPanel1.add(id_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 130, 30));

        nombre_vc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nombre_vc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_vcKeyTyped(evt);
            }
        });
        jPanel1.add(nombre_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 130, 30));

        peso_vc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        peso_vc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                peso_vcKeyTyped(evt);
            }
        });
        jPanel1.add(peso_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 130, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Operaciones");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 760, 50));

        cr_lim.setBackground(new java.awt.Color(0, 204, 204));
        cr_lim.setLayout(new java.awt.CardLayout());

        eliminar_vc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        eliminar_vc.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_vc.setText("Eliminar");
        eliminar_vc.setContentAreaFilled(false);
        eliminar_vc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminar_vcMousePressed(evt);
            }
        });
        eliminar_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_vcActionPerformed(evt);
            }
        });
        cr_lim.add(eliminar_vc, "card2");

        jPanel1.add(cr_lim, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 100, 30));

        rc_mod.setBackground(new java.awt.Color(0, 204, 204));
        rc_mod.setLayout(new java.awt.CardLayout());

        modi_vc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modi_vc.setForeground(new java.awt.Color(255, 255, 255));
        modi_vc.setText("Modificar");
        modi_vc.setContentAreaFilled(false);
        modi_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modi_vcActionPerformed(evt);
            }
        });
        rc_mod.add(modi_vc, "card2");

        jPanel1.add(rc_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 100, 30));

        rc_guar.setBackground(new java.awt.Color(0, 204, 204));
        rc_guar.setLayout(new java.awt.CardLayout());

        guar_vc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        guar_vc.setForeground(new java.awt.Color(255, 255, 255));
        guar_vc.setText("Guardar");
        guar_vc.setContentAreaFilled(false);
        guar_vc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guar_vcMousePressed(evt);
            }
        });
        guar_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guar_vcActionPerformed(evt);
            }
        });
        rc_guar.add(guar_vc, "card2");

        jPanel1.add(rc_guar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 100, 30));

        sexo_vc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sexo_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo_vcActionPerformed(evt);
            }
        });
        jPanel1.add(sexo_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 130, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pelaje");
        jPanel5.add(jLabel12);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 70, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel6.add(jLabel7);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 70, 30));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("F/N");
        jPanel7.add(jLabel10);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 70, 30));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        jPanel8.add(jLabel2);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peso");
        jPanel9.add(jLabel4);

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 70, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Raza");
        jPanel10.add(jLabel3);

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 70, 30));
        jPanel1.add(jLabel_1clint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 20));
        jPanel1.add(jLabel_2clint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, 20));
        jPanel1.add(jLabel_3clint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 20));
        jPanel1.add(jLabel_4clint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 130, 20));
        jPanel1.add(jLabel_5clint, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 130, 20));
        jPanel1.add(jLabel_6clint, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 130, 20));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");
        jPanel11.add(jLabel1);

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 70, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Madre");
        jPanel12.add(jLabel9);

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 70, 30));

        id_vc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_vc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_vcKeyTyped(evt);
            }
        });
        jPanel1.add(id_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 30));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Padre");
        jPanel13.add(jLabel5);

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 30));

        id_madre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_madre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_madreKeyTyped(evt);
            }
        });
        jPanel1.add(id_madre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 130, 30));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sexo");
        jPanel14.add(jLabel8);

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 70, 30));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Color");
        jPanel15.add(jLabel11);

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 70, 30));

        pelaje_vc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pelaje_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelaje_vcActionPerformed(evt);
            }
        });
        jPanel1.add(pelaje_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 130, 30));

        color_vc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        color_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_vcActionPerformed(evt);
            }
        });
        jPanel1.add(color_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 130, 30));

        rc_guar1.setBackground(new java.awt.Color(0, 204, 204));
        rc_guar1.setLayout(new java.awt.CardLayout());

        limpia_vc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limpia_vc.setForeground(new java.awt.Color(255, 255, 255));
        limpia_vc.setText("Limpiar");
        limpia_vc.setContentAreaFilled(false);
        limpia_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpia_vcActionPerformed(evt);
            }
        });
        rc_guar1.add(limpia_vc, "card2");

        jPanel1.add(rc_guar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 100, 30));

        raza_vc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        raza_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raza_vcActionPerformed(evt);
            }
        });
        jPanel1.add(raza_vc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 130, 30));
        jPanel1.add(jLabel_6clint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 130, 20));
        jPanel1.add(jLabel_6clint2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 130, 20));
        jPanel1.add(jLabel_6clint3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 130, 20));
        jPanel1.add(jLabel_6clint4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 130, 20));
        jPanel1.add(jLabel_6clint5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 130, 20));

        rc_guar2.setBackground(new java.awt.Color(0, 204, 204));
        rc_guar2.setLayout(new java.awt.CardLayout());

        detalles_vc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        detalles_vc.setForeground(new java.awt.Color(255, 255, 255));
        detalles_vc.setText("Detalles");
        detalles_vc.setContentAreaFilled(false);
        detalles_vc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_vcActionPerformed(evt);
            }
        });
        rc_guar2.add(detalles_vc, "card2");

        jPanel1.add(rc_guar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 100, 30));
        jPanel1.add(fecha_vca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 130, 30));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void guar_vcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guar_vcMousePressed

        if (id_vc.getText().trim().isEmpty() || id_padre.getText().trim().isEmpty() || fecha_vca.getDate() == null || nombre_vc.getText().trim().isEmpty() || peso_vc.getText().trim().isEmpty() || id_madre.getText().trim().isEmpty() || raza_vc.getSelectedIndex() == 0 || sexo_vc.getSelectedIndex() == 0 || pelaje_vc.getSelectedIndex() == 0 || color_vc.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Campos Vacios");
            validar_campos.validarCampoVacio(id_padre, jLabel_6clint5);
            validar_campos.validarCampoVacio(nombre_vc, jLabel_4clint);
            validar_campos.validarCampoVacio(peso_vc, jLabel_5clint);
            validar_campos.validarCampoVacio(id_vc, jLabel_2clint);
            validar_campos.validarCampoVacio(id_madre, jLabel_6clint2);

            boolean valido = true;

            valido &= validar_campos.validarCombo(sexo_vc, jLabel_6clint4);
            valido &= validar_campos.validarCombo(raza_vc, jLabel_6clint1);
            valido &= validar_campos.validarCombo(pelaje_vc, jLabel_6clint);
            valido &= validar_campos.validarCombo(color_vc, jLabel_6clint3);

            if (!valido) {
                return;
            }

        } else {
            int id_va = Integer.valueOf(id_vc.getText());
            Date fechaSeleccionada = fecha_vca.getDate();
            SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
            String fecha = formato.format(fechaSeleccionada);
            String nombre_va = String.valueOf(nombre_vc.getText());
            double pes = Double.valueOf(peso_vc.getText());
            int madr = Integer.valueOf(id_madre.getText());
            int padr = Integer.valueOf(id_padre.getText());
            int codi = Integer.valueOf(id_vc.getText());
            int pregun = JOptionPane.showConfirmDialog(null, "Quiere Guardar los Datos ?");
            if (pregun == 0) {
                animal an = new animal();
                an.setCodigo(codi);
                an.setFechanacimiento(fecha);
                an.setNombre(nombre_va);
                an.setPeso(pes);
                an.setId_raza(idraza);
                an.setMadre(madr);
                an.setPadre(padr);
                an.setId_sexo(idsexo);
                an.setId_color(idcolor);
                an.setId_pelaje(idpelaje);
                an.setId_raza(idraza);
                an.requestOne(codi);
                int pre = an.getCodigo();
                if (pre != 0) {
                    an.save();
                    JOptionPane.showMessageDialog(this, "Los Datos se Guardaron Correctamente");
                    this.id_vc.setText("");
                    this.fecha_vca.setCalendar(null);
                    this.nombre_vc.setText("");
                    this.id_madre.setText("");
                    this.id_padre.setText("");
                    this.peso_vc.setText("");
                    carga.consul_sexo(sexo_vc);
                    carga.consul_color(color_vc);
                    carga.consul_pelaje(pelaje_vc);
                    carga.consul_raz(raza_vc);
                } else {
                    JOptionPane.showMessageDialog(this, "Error ya Existe Este Registro");
                    this.id_vc.setText("");
                    this.fecha_vca.setCalendar(null);
                    this.nombre_vc.setText("");
                    this.id_madre.setText("");
                    this.id_padre.setText("");
                    this.peso_vc.setText("");
                    carga.consul_sexo(sexo_vc);
                    carga.consul_color(color_vc);
                    carga.consul_pelaje(pelaje_vc);
                    carga.consul_raz(raza_vc);
                }

            }

            /*if ("Seleccione".equals(seleccion)) {
                int cedu_cli = Integer.valueOf(id_padre.getText());
                String nombre_cli = String.valueOf(fecha_vc.getText());
                String apelli_cli = String.valueOf(nombre_vc.getText());
                String tlf_cli = String.valueOf(peso_vc.getText());
                String direc_cli = String.valueOf(raza_vc.getText());
                int pregun = JOptionPane.showConfirmDialog(null,"Desea Guardar el Cliente ?");
                if (pregun == 0) {
                    cliente clien = new cliente();
                    clien.setCedula(cedu_cli);
                    clien.setNombre(nombre_cli);
                    clien.setApellido(apelli_cli);
                    clien.setTelefono(tlf_cli);
                    clien.setDireccion(direc_cli);
                    clien.requestOne(cedu_cli);
                    int consul = clien.getCedula();
                    if (consul == 0) {
                        clien.save();

                        JOptionPane.showMessageDialog(this, "Los Datos se Guardaron Correctamente");
                        this.id_padre.setText("");
                        this.fecha_vc.setText("");
                        this.nombre_vc.setText("");
                        this.peso_vc.setText("");
                        this.raza_vc.setText("");
                        carga.consul_grup(sexo_vc);
                    }else{
                        JOptionPane.showMessageDialog(null, "Cliente ya Esta Registro");
                        this.id_padre.setText("");
                        this.fecha_vc.setText("");
                        this.nombre_vc.setText("");
                        this.peso_vc.setText("");
                        this.raza_vc.setText("");
                        carga.consul_grup(sexo_vc);
                    }
                   

                }else{
                    this.id_padre.setText("");
                    this.fecha_vc.setText("");
                    this.nombre_vc.setText("");
                    this.peso_vc.setText("");
                    this.raza_vc.setText("");
                    carga.consul_grup(sexo_vc);

                }           
            }else{
                if (contador >= 48) {
                    JOptionPane.showMessageDialog(null, "Grupo LLeno");
                    this.id_padre.setText("");
                    this.fecha_vc.setText("");
                    this.nombre_vc.setText("");
                    this.peso_vc.setText("");
                    this.raza_vc.setText("");
                    carga.consul_grup(sexo_vc);
                }else{
                    int cedu_cli = Integer.valueOf(id_padre.getText());
                    String nombre_cli = String.valueOf(fecha_vc.getText());
                    String apelli_cli = String.valueOf(nombre_vc.getText());
                    String tlf_cli = String.valueOf(peso_vc.getText());
                    String direc_cli = String.valueOf(raza_vc.getText());
                    int pregun = JOptionPane.showConfirmDialog(null,"Desea Guardar el Cliente ?");
                 if (pregun == 0) {
                    cliente clien = new cliente();
                    grupo gru = new grupo();
                    clien.setId_grupo(idgrupo);
                    clien.setCedula(cedu_cli);
                    clien.setNombre(nombre_cli);
                    clien.setApellido(apelli_cli);
                    clien.setTelefono(tlf_cli);
                    clien.setDireccion(direc_cli);
                    clien.save();
                    contador ++;
                    gru.setContador(contador);
                    gru.setId(idgrupo);
                    gru.update();
                    JOptionPane.showMessageDialog(this, "Los Datos se Guardaron Correctamente");
                    this.id_padre.setText("");
                    this.fecha_vc.setText("");
                    this.nombre_vc.setText("");
                    this.peso_vc.setText("");
                    this.raza_vc.setText("");
                    carga.consul_grup(sexo_vc);
                 }
                }
               
            }*/
        }

    }//GEN-LAST:event_guar_vcMousePressed

    private void modi_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modi_vcActionPerformed
        // TODO add your handling code here:
        if (id_vc.getText().trim().isEmpty() || id_padre.getText().trim().isEmpty() || fecha_vca.getDate() == null || nombre_vc.getText().trim().isEmpty() || peso_vc.getText().trim().isEmpty() || id_madre.getText().trim().isEmpty() || raza_vc.getSelectedIndex() == 0 || sexo_vc.getSelectedIndex() == 0 || pelaje_vc.getSelectedIndex() == 0 || color_vc.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Campos Vacios");

        } else {
            int id_va = Integer.valueOf(id_vc.getText());
            double pes = Double.valueOf(peso_vc.getText());

            int pregunta = JOptionPane.showConfirmDialog(null, "Desea Modificar los Datos ?");
            if (pregunta == 0) {
                animal an = new animal();
                an.setCodigo(id_va);
                an.setPeso(pes);
                an.setId_raza(idraza);
                an.update();
                JOptionPane.showConfirmDialog(null, "Datos Modificados Correctamente");
                this.id_vc.setText("");
                this.fecha_vca.setCalendar(null);
                this.nombre_vc.setText("");
                this.id_madre.setText("");
                this.id_padre.setText("");
                this.peso_vc.setText("");
                this.tex_buscRC.setText("");
                carga.consul_sexo(sexo_vc);
                carga.consul_color(color_vc);
                carga.consul_pelaje(pelaje_vc);
                carga.consul_raz(raza_vc);
            } else {
                JOptionPane.showMessageDialog(this, "Error ya Existe Este Registro");
                this.id_vc.setText("");
                this.fecha_vca.setCalendar(null);
                this.nombre_vc.setText("");
                this.id_madre.setText("");
                this.id_padre.setText("");
                this.peso_vc.setText("");
                carga.consul_sexo(sexo_vc);
                carga.consul_color(color_vc);
                carga.consul_pelaje(pelaje_vc);
                carga.consul_raz(raza_vc);
            }
        }

    }//GEN-LAST:event_modi_vcActionPerformed

    private void limpia_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpia_vcActionPerformed
        // TODO add your handling code here:

        this.id_padre.setText("");
        this.fecha_vca.setCalendar(null);
        this.nombre_vc.setText("");
        this.tex_buscRC.setText("");
        this.peso_vc.setText("");
    }//GEN-LAST:event_limpia_vcActionPerformed

    private void sexo_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo_vcActionPerformed
        // TODO add your handling code here:
        Object sexoseleccionado = sexo_vc.getSelectedItem();
        if (sexoseleccionado instanceof models.sexo) {
            models.sexo selectsexo = (models.sexo) sexoseleccionado;
            idsexo = selectsexo.getId();
        }
    }//GEN-LAST:event_sexo_vcActionPerformed

    private void id_padreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_padreKeyTyped
        id_padre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (id_padre.getText().length() >= 8) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_id_padreKeyTyped

    private void nombre_vcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_vcKeyTyped
        nombre_vc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (nombre_vc.getText().length() >= 15) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_nombre_vcKeyTyped

    private void peso_vcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_peso_vcKeyTyped
        peso_vc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (peso_vc.getText().length() >= 11) {
                    e.consume();
                }
            }
        });
    }//GEN-LAST:event_peso_vcKeyTyped

    public String obtenerNombresexoPorId(int id) {
        switch (id) {
            case 1:
                return "Hebra";
            case 2:
                return "Macho";
            default:
                return null;
        }
    }

    public String obtenerNombrepelajePorId(int id) {
        switch (id) {
            case 1:
                return "Corto";
            case 2:
                return "Mediano";
            case 3:
                return "Largo";
            default:
                return null;
        }
    }


    private void tex_buscRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tex_buscRCActionPerformed
        // TODO add your handling code here:
        String campodato = tex_buscRC.getText();

        if (campodato.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Vacio para Realizar Busqueda");
            return;
        }

        try {

            animal anDAO = new animal();
            int codi = Integer.parseInt(campodato);

            anDAO.requestOne(codi);

            int idInterno = anDAO.getId();

            if (idInterno == 0) {
                JOptionPane.showMessageDialog(null, "Animal No Existente");
                this.idAnimalInterno = 0;
                this.animalEncontrado = null;

            } else {

                this.animalEncontrado = anDAO;
                this.idAnimalInterno = idInterno;

                id_vc.setText(String.valueOf(anDAO.getCodigo()));
                nombre_vc.setText(anDAO.getNombre());
                peso_vc.setText(String.valueOf(anDAO.getPeso()));
                id_madre.setText(String.valueOf(anDAO.getMadre()));
                id_padre.setText(String.valueOf(anDAO.getPadre()));

                try {
                    SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
                    Date fechaConvertida = formato.parse(anDAO.getFechanacimiento());
                    fecha_vca.setDate(fechaConvertida);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al convertir la fecha: " + e.getMessage());
                }

                razaid = anDAO.getId_raza();
                for (int i = 0; i < raza_vc.getItemCount(); i++) {
                    Object llenamar = raza_vc.getItemAt(i);
                    if (llenamar instanceof models.raza) {
                        models.raza razaiten = (models.raza) llenamar;
                        if (razaiten.getId() == razaid) {
                            raza_vc.setSelectedItem(razaiten);
                            break;
                        }
                    }
                }

                sexoid = anDAO.getId_sexo();
                for (int i = 0; i < sexo_vc.getItemCount(); i++) {
                    Object llenamar = sexo_vc.getItemAt(i);
                    if (llenamar instanceof models.sexo) {
                        models.sexo sexoiten = (models.sexo) llenamar;
                        if (sexoiten.getId() == sexoid) {
                            sexo_vc.setSelectedItem(sexoiten);
                            break;
                        }
                    }
                }

                colorid = anDAO.getId_color();
                for (int i = 0; i < color_vc.getItemCount(); i++) {
                    Object llenamar = color_vc.getItemAt(i);
                    if (llenamar instanceof models.color) {
                        models.color coloriten = (models.color) llenamar;
                        if (coloriten.getId() == colorid) {
                            color_vc.setSelectedItem(coloriten);
                            break;
                        }
                    }
                }

                pelejeid = anDAO.getId_pelaje();
                for (int i = 0; i < pelaje_vc.getItemCount(); i++) {
                    Object llenamar = pelaje_vc.getItemAt(i);
                    if (llenamar instanceof models.pelaje) {
                        models.pelaje pelajeiten = (models.pelaje) llenamar;
                        if (pelajeiten.getId() == pelejeid) {
                            pelaje_vc.setSelectedItem(pelajeiten);
                            break;
                        }
                    }
                }

                tex_buscRC.setText("");
                fecha_vca.requestFocus();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Codigo inválido. Debe ser un número.");
        }


    }//GEN-LAST:event_tex_buscRCActionPerformed

    private void id_vcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_vcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id_vcKeyTyped

    private void id_madreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_madreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_id_madreKeyTyped

    private void pelaje_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelaje_vcActionPerformed
        // TODO add your handling code here:
        Object pelajeseleccion = pelaje_vc.getSelectedItem();
        if (pelajeseleccion instanceof models.pelaje) {
            models.pelaje selectpelaje = (models.pelaje) pelajeseleccion;
            idpelaje = selectpelaje.getId();
        }
    }//GEN-LAST:event_pelaje_vcActionPerformed

    private void color_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_vcActionPerformed
        // TODO add your handling code here:
        Object colorseleccion = color_vc.getSelectedItem();
        if (colorseleccion instanceof String) {
            String cl = (String) colorseleccion;
            if ("Agregar".equals(cl)) {
                while (true) {
                    color col = new color();
                    String newcolor = JOptionPane.showInputDialog(null, "Ingrese un Nuevo Color");
                    while (newcolor != null) {
                        col.requestOne(newcolor);
                        String obtener = col.getColor();
                        if (obtener == null) {
                            col.setColor(newcolor);
                            col.save();
                            JOptionPane.showMessageDialog(null, "Registro Exitoso");
                            carga.consul_color(color_vc);
                            conexion.desconectar();
                            break;
                        } else {
                            JOptionPane.showMessageDialog(null, "Color Ya Existe");
                            break;
                        }

                    }
                    break;
                }
            }

        } else if (colorseleccion instanceof models.color) {
            models.color selectcolor = (models.color) colorseleccion;
            idcolor = selectcolor.getId();
        }
    }//GEN-LAST:event_color_vcActionPerformed

    private void guar_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guar_vcActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_guar_vcActionPerformed

    private void eliminar_vcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_vcMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_vcMousePressed

    private void eliminar_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_vcActionPerformed
        // TODO add your handling code here:
        if (this.id_vc.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ningún animal seleccionado para eliminar.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar este animal?\nEsta acción no se puede deshacer.",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirmacion == JOptionPane.YES_OPTION) {
            int codigo = Integer.parseInt(this.id_vc.getText().trim());

            animal dao = new animal();
            dao.setCodigo(codigo);

            int resultado = dao.deleteuno(codigo);

            if (resultado == 1) {
                JOptionPane.showMessageDialog(this, "El animal ha sido eliminado exitosamente.");
                this.id_vc.setText("");
                this.fecha_vca.setCalendar(null);
                this.nombre_vc.setText("");
                this.id_madre.setText("");
                this.id_padre.setText("");
                this.peso_vc.setText("");
                this.tex_buscRC.setText("");
                carga.consul_sexo(sexo_vc);
                carga.consul_color(color_vc);
                carga.consul_pelaje(pelaje_vc);
                carga.consul_raz(raza_vc);

            } else if (resultado == 0) {
                JOptionPane.showMessageDialog(this, "No se encontró el animal para eliminar.");
                this.id_vc.setText("");
                this.fecha_vca.setCalendar(null);
                this.nombre_vc.setText("");
                this.id_madre.setText("");
                this.id_padre.setText("");
                this.peso_vc.setText("");
                this.tex_buscRC.setText("");
                carga.consul_sexo(sexo_vc);
                carga.consul_color(color_vc);
                carga.consul_pelaje(pelaje_vc);
                carga.consul_raz(raza_vc);
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar eliminar el animal.");
                this.id_vc.setText("");
                this.fecha_vca.setCalendar(null);
                this.nombre_vc.setText("");
                this.id_madre.setText("");
                this.id_padre.setText("");
                this.peso_vc.setText("");
                this.tex_buscRC.setText("");
                carga.consul_sexo(sexo_vc);
                carga.consul_color(color_vc);
                carga.consul_pelaje(pelaje_vc);
                carga.consul_raz(raza_vc);

            }

        }

    }//GEN-LAST:event_eliminar_vcActionPerformed

    private void raza_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raza_vcActionPerformed
        // TODO add your handling code here:
        Object razaseleccion = raza_vc.getSelectedItem();
        if (razaseleccion instanceof String) {
            String ra = (String) razaseleccion;
            if ("Agregar".equals(ra)) {
                while (true) {
                    raza rz = new raza();
                    String newraza = JOptionPane.showInputDialog(null, "Ingrese una Nueva Raza");
                    while (newraza != null) {
                        rz.requestOne(newraza);
                        String obtener = rz.getRaza();
                        if (obtener == null) {
                            rz.setRaza(newraza);
                            rz.save();
                            JOptionPane.showMessageDialog(null, "Registro Exitoso");
                            carga.consul_raz(raza_vc);
                            conexion.desconectar();
                            break;
                        } else {
                            JOptionPane.showMessageDialog(null, "Raza Ya Existe");
                            break;
                        }

                    }
                    break;
                }
            }

        } else if (razaseleccion instanceof models.raza) {
            models.raza selectraza = (models.raza) razaseleccion;
            idraza = selectraza.getId();
        }
    }//GEN-LAST:event_raza_vcActionPerformed

    private void detalles_vcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_vcActionPerformed
        // TODO add your handling code here:
        if (this.idAnimalInterno <= 0 || this.animalEncontrado == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Primero debe buscar y cargar un animal válido.",
                    "Acción Requerida",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Búsqueda del Frame Padre
        java.awt.Frame parentFrame = javax.swing.JOptionPane.getFrameForComponent(this);

        if (parentFrame == null) {
            parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        }

        java.awt.Frame framePadreFinal = (parentFrame != null) ? parentFrame : null;

        // 🛑 LLAMADA AL CONSTRUCTOR CORREGIDA (Pasando los 5 parámetros) 🛑
        registro dialogo = new registro(
                framePadreFinal, // 1. Frame Padre
                true, // 2. Modal
                this.idAnimalInterno, // 3. ID Interno (Llave Primaria)
                String.valueOf(this.animalEncontrado.getCodigo()), // 4. Código del Animal (String)
                this.animalEncontrado.getNombre() // 5. Nombre del Animal (String)
        );

        dialogo.setLocationRelativeTo(framePadreFinal);
        dialogo.setVisible(true);


    }//GEN-LAST:event_detalles_vcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> color_vc;
    public javax.swing.JPanel cr_lim;
    public javax.swing.JButton detalles_vc;
    public javax.swing.JButton eliminar_vc;
    private com.toedter.calendar.JDateChooser fecha_vca;
    public javax.swing.JButton guar_vc;
    private javax.swing.JTextField id_madre;
    private javax.swing.JTextField id_padre;
    private javax.swing.JTextField id_vc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_1clint;
    private javax.swing.JLabel jLabel_2clint;
    private javax.swing.JLabel jLabel_3clint;
    private javax.swing.JLabel jLabel_4clint;
    private javax.swing.JLabel jLabel_5clint;
    private javax.swing.JLabel jLabel_6clint;
    private javax.swing.JLabel jLabel_6clint1;
    private javax.swing.JLabel jLabel_6clint2;
    private javax.swing.JLabel jLabel_6clint3;
    private javax.swing.JLabel jLabel_6clint4;
    private javax.swing.JLabel jLabel_6clint5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JButton limpia_vc;
    public javax.swing.JButton modi_vc;
    private javax.swing.JTextField nombre_vc;
    private javax.swing.JComboBox<String> pelaje_vc;
    private javax.swing.JTextField peso_vc;
    private javax.swing.JComboBox<String> raza_vc;
    public javax.swing.JPanel rc_guar;
    public javax.swing.JPanel rc_guar1;
    public javax.swing.JPanel rc_guar2;
    public javax.swing.JPanel rc_mod;
    private javax.swing.JComboBox<String> sexo_vc;
    private javax.swing.JTextField tex_buscRC;
    // End of variables declaration//GEN-END:variables
class fondo extends JPanel {

        Image imag;

        @Override
        public void paint(Graphics g) {

            imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();

            g.drawImage(imag, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }

    }
}
