/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import control.Controller7;
import control.cargar_combx;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.WindowConstants;
import javax.swing.JDialog;
import java.awt.Frame;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableCellRenderer;
import com.itextpdf.text.Document;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.print.PrinterException;
import java.io.*;
import javax.swing.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.*;
import java.awt.Desktop;
import java.net.URL;
import com.itextpdf.text.Element;
import common.conexion;
import models.enfermedad;
import models.raza;
import models.vacuna;
import models.ve_registro;
import java.util.List;
import java.util.ArrayList;







/**
 *
 * @author User
 */
public class registro extends javax.swing.JDialog {
    cargar_combx carga = new cargar_combx();
    public Controller7 controller;
    private String tipoOperacion;
    private String tipoDeTiempo;
    int idvacuna = 0, idenfer = 0;
    
   private int idVacaActual;
   private String codigoVaca; 
   private String nombreVaca;

    public registro(Frame parent, boolean modal, int idAnimal, String codigoAnimal, String nombreAnimal){
        super(parent, modal);
        initComponents();
        carga.consul_medi(medici_va);
        carga.consul_enfer(enfer_va);
        
        this.idVacaActual = idAnimal;
        this.codigoVaca = codigoAnimal; 
        this.nombreVaca = nombreAnimal;
        cargarRegistrosEnTabla(); 
        this.setSize(800, 600); 
    this.setPreferredSize(new java.awt.Dimension(800, 600)); 
    this.pack(); 
    this.setLocationRelativeTo(null);
    }
    public registro(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    
    this.idVacaActual = 0; 
    this.codigoVaca = "";
    this.nombreVaca = "NUEVO REGISTRO";
    }

    private void cargarRegistrosEnTabla() {
    
    DefaultTableModel model = (DefaultTableModel) Table_detalles.getModel();
    model.setRowCount(0); 
    
    int idParaConsultar = this.idVacaActual;
    
    ve_registro dao = new ve_registro(); 
   
       var registrosEncontrados = dao.obtenerRegistros(idParaConsultar); 

    for (Object[] fila : registrosEncontrados) {
        model.addRow(fila);
    }
}
    


    
    
      public void setTipoDeTiempo(String tipoDeTiempo) {
        this.tipoDeTiempo = tipoDeTiempo;
    }

    
    public void setTipoOperacion(String tipo) {
    this.tipoOperacion = tipo;
    
    }
    
    
    
    
    
    
    
    
    
    
    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo();
        jLabel5 = new javax.swing.JLabel();
        ts_guar = new javax.swing.JPanel();
        Ts_guard = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_detalles = new javax.swing.JTable();
        ts_guar1 = new javax.swing.JPanel();
        ts_cargar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ts_guar2 = new javax.swing.JPanel();
        reporte = new javax.swing.JButton();
        enfer_va = new javax.swing.JComboBox<>();
        medici_va = new javax.swing.JComboBox<>();
        fecha_va = new com.toedter.calendar.JDateChooser();

        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        ts_guar.setBackground(new java.awt.Color(0, 204, 204));
        ts_guar.setLayout(new java.awt.CardLayout());

        Ts_guard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Ts_guard.setForeground(new java.awt.Color(255, 255, 255));
        Ts_guard.setText("Guardar");
        Ts_guard.setContentAreaFilled(false);
        Ts_guard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ts_guardActionPerformed(evt);
            }
        });
        ts_guar.add(Ts_guard, "card2");

        jPanel1.add(ts_guar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 100, 40));

        Table_detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Medicina", "Enfermedad", "Fecha"
            }
        ));
        jScrollPane2.setViewportView(Table_detalles);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 460, 380));

        ts_guar1.setBackground(new java.awt.Color(0, 204, 204));
        ts_guar1.setLayout(new java.awt.CardLayout());

        ts_cargar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ts_cargar.setForeground(new java.awt.Color(255, 255, 255));
        ts_cargar.setText("Cargar");
        ts_cargar.setContentAreaFilled(false);
        ts_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_cargarActionPerformed(evt);
            }
        });
        ts_guar1.add(ts_cargar, "card2");

        jPanel1.add(ts_guar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 100, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Enfermedad ");
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("fecha");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 90, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Medicina");
        jPanel4.add(jLabel4);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 30));

        ts_guar2.setBackground(new java.awt.Color(0, 204, 204));
        ts_guar2.setLayout(new java.awt.CardLayout());

        reporte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reporte.setForeground(new java.awt.Color(255, 255, 255));
        reporte.setText("Reporte");
        reporte.setContentAreaFilled(false);
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });
        ts_guar2.add(reporte, "card2");

        jPanel1.add(ts_guar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 100, 40));

        enfer_va.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enfer_va.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfer_vaActionPerformed(evt);
            }
        });
        jPanel1.add(enfer_va, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, 30));

        medici_va.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        medici_va.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medici_vaActionPerformed(evt);
            }
        });
        jPanel1.add(medici_va, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 110, 30));
        jPanel1.add(fecha_va, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 100, 30));

        getContentPane().add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void ts_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_cargarActionPerformed
        // TODO add your handling code here:
     String medicina = medici_va.getSelectedItem().toString(); 
    String enfermedad = enfer_va.getSelectedItem().toString();
    
    Date fechaSeleccionada = fecha_va.getDate(); 
    String fecha = ""; 
    
    if (medicina.equals("Seleccione") || enfermedad.equals("Seleccione") || fechaSeleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe seleccionar una Medicina, una Enfermedad y una Fecha válida.", 
            "Datos Faltantes", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
   
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fecha = sdf.format(fechaSeleccionada);
    } catch (Exception e) {
   
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al procesar la fecha.", 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }


    DefaultTableModel model = (DefaultTableModel) Table_detalles.getModel();
    
   
    Object[] nuevaFila = new Object[] {
        medicina,
        enfermedad,
        fecha
    };
    
  
    model.addRow(nuevaFila);
  
    medici_va.setSelectedIndex(0);
    enfer_va.setSelectedIndex(0);
    fecha_va.setDate(null); 
    }//GEN-LAST:event_ts_cargarActionPerformed

    private void Ts_guardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ts_guardActionPerformed
        // TODO add your handling code here:                                                                                      
   DefaultTableModel model = (DefaultTableModel) Table_detalles.getModel();
    
    List<Object[]> registrosAGuardar = new ArrayList<>();
    for (int i = 0; i < model.getRowCount(); i++) {
        Object[] fila = new Object[]{
            model.getValueAt(i, 0), 
            model.getValueAt(i, 1), 
            model.getValueAt(i, 2)  
        };
        registrosAGuardar.add(fila);
    }
    
    ve_registro dao = new ve_registro();
    boolean exito = dao.saveid(this.idVacaActual, registrosAGuardar); 
    
    if (exito) {
        javax.swing.JOptionPane.showMessageDialog(this, "Registros guardados exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        this.dispose(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Hubo un error al guardar los registros. Revise los nombres o la conexión a la BD.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_Ts_guardActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        // TODO add your handling code here:
    if (this.idVacaActual <= 0) {
        JOptionPane.showMessageDialog(this, "No hay un animal seleccionado para generar el reporte.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar Reporte Clínico PDF");
    
    String nombreSugerido = "Reporte_Clinico_" + this.codigoVaca + ".pdf";
    fileChooser.setSelectedFile(new File(nombreSugerido));
    
  
    int userSelection = fileChooser.showSaveDialog(this);

   
    if (userSelection != JFileChooser.APPROVE_OPTION) {
        JOptionPane.showMessageDialog(this, "Operación de guardado cancelada.");
        return;
    }

   
    File file = fileChooser.getSelectedFile();
    String nombreArchivoBase = file.getName();
    
    if (!nombreArchivoBase.toLowerCase().endsWith(".pdf")) {
        file = new File(file.getAbsolutePath() + ".pdf");
        nombreArchivoBase += ".pdf"; 
    }
    
    try {
        Document documento = new Document(PageSize.LETTER, 25, 25, 25, 25);
        PdfWriter.getInstance(documento, new FileOutputStream(file));
        documento.open();

        Font tituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.BLACK);
        Font subtituloFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.DARK_GRAY);
        Font textoFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.BLACK);
        Font encabezadoTablaFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, BaseColor.WHITE);
        
        PdfPTable encabezado = new PdfPTable(1); 
        encabezado.setWidthPercentage(100);

        PdfPCell celdaTitulo = new PdfPCell();
        celdaTitulo.setBorder(Rectangle.NO_BORDER);
        celdaTitulo.setHorizontalAlignment(Element.ALIGN_LEFT); 
        celdaTitulo.setVerticalAlignment(Element.ALIGN_MIDDLE);
        celdaTitulo.addElement(new Paragraph("SISTEMA DE GESTIÓN GANADERA", tituloFont));
        celdaTitulo.addElement(new Paragraph("REPORTE CLÍNICO DEL ANIMAL", subtituloFont));
        encabezado.addCell(celdaTitulo);
        
        documento.add(encabezado);
        documento.add(new Paragraph(" "));
        
        documento.add(new Paragraph("Código: " + this.codigoVaca, textoFont)); 
        documento.add(new Paragraph("Nombre: " + this.nombreVaca, textoFont)); 
        documento.add(new Paragraph("ID Interno: " + this.idVacaActual, textoFont));
        documento.add(new Paragraph("Fecha de Reporte: " + new SimpleDateFormat("dd/MM/yyyy").format(new Date()), textoFont));
        documento.add(new Paragraph(" "));
        documento.add(new Paragraph(" "));

        DefaultTableModel model = (DefaultTableModel) Table_detalles.getModel();
        
        PdfPTable tabla = new PdfPTable(3); 
        tabla.setWidthPercentage(100);
        tabla.setWidths(new float[]{3f, 3f, 2f});

        String[] encabezadosTabla = {"MEDICINA/VACUNA", "ENFERMEDAD/SÍNTOMA", "FECHA"};
        for (String encabezad : encabezadosTabla) {
            PdfPCell celda = new PdfPCell(new Phrase(encabezad, encabezadoTablaFont));
            celda.setHorizontalAlignment(PdfPCell.ALIGN_CENTER); 
            celda.setBackgroundColor(BaseColor.DARK_GRAY); 
            celda.setPadding(6f);
            tabla.addCell(celda);
        }
        
        if (model.getRowCount() == 0) {
            PdfPCell celdaVacia = new PdfPCell(new Phrase("No se encontraron registros clínicos para este animal.", textoFont));
            celdaVacia.setColspan(3);
            celdaVacia.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
            celdaVacia.setPadding(10f);
            tabla.addCell(celdaVacia);
        } else {
            for (int i = 0; i < model.getRowCount(); i++) {
                String medicina = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString() : "";
                String enfermedad = model.getValueAt(i, 1) != null ? model.getValueAt(i, 1).toString() : "";
                String fecha = model.getValueAt(i, 2) != null ? model.getValueAt(i, 2).toString() : "";

                tabla.addCell(new PdfPCell(new Phrase(medicina, textoFont)));
                tabla.addCell(new PdfPCell(new Phrase(enfermedad, textoFont)));
                tabla.addCell(new PdfPCell(new Phrase(fecha, textoFont)));
            }
        }

        documento.add(tabla);
        documento.close();

        if (Desktop.isDesktopSupported() && file.exists()) {
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);
        }
        JOptionPane.showMessageDialog(this, "Reporte '" + nombreArchivoBase + "' guardado y abierto correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al generar el PDF: " + e.getMessage(), "Error de Reporte", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_reporteActionPerformed

    private void medici_vaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medici_vaActionPerformed
        // TODO add your handling code here:
        Object mediseleccion = medici_va.getSelectedItem();
        if(mediseleccion instanceof String){
            String me = (String) mediseleccion;
            if ("Agregar".equals(me)) {
                while (true) {                    
                    vacuna va = new vacuna();
                    String newvacu = JOptionPane.showInputDialog(null,"Ingrese una Nueva Vacuna");
                    while (newvacu != null) {                        
                        va.requestOne(newvacu);
                        String obtener = va.getVacuna();
                        if(obtener == null){
                            va.setVacuna(newvacu);
                            va.save();
                            JOptionPane.showMessageDialog(null,"Registro Exitoso");
                            carga.consul_medi(medici_va);
                            conexion.desconectar();
                            break;
                        }else{
                        JOptionPane.showMessageDialog(null,"Vacuna Ya Existe");
                        break;
                        }
                        
                    }
                    break;
                }
            }
            
        }else if (mediseleccion instanceof models.vacuna) {
            models.vacuna selectvacu = (models.vacuna) mediseleccion;
            idvacuna = selectvacu.getId();
        }
    }//GEN-LAST:event_medici_vaActionPerformed

    private void enfer_vaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfer_vaActionPerformed
        // TODO add your handling code here:
           Object enferseleccion = enfer_va.getSelectedItem();
        if(enferseleccion instanceof String){
            String me = (String) enferseleccion;
            if ("Agregar".equals(me)) {
                while (true) {                    
                    enfermedad en = new enfermedad();
                    String newenfer = JOptionPane.showInputDialog(null,"Ingrese una Nueva enfermedad");
                    while (newenfer != null) {                        
                        en.requestOne(newenfer);
                        String obtener = en.getEnfermedad();
                        if(obtener == null){
                            en.setEnfermedad(newenfer);
                            en.save();
                            JOptionPane.showMessageDialog(null,"Registro Exitoso");
                            carga.consul_enfer(enfer_va);
                            conexion.desconectar();
                            break;
                        }else{
                        JOptionPane.showMessageDialog(null,"Enfermedad Ya Existe");
                        break;
                        }
                        
                    }
                    break;
                }
            }
            
        }else if (enferseleccion instanceof models.enfermedad) {
            models.enfermedad selectenfer = (models.enfermedad) enferseleccion;
            idenfer = selectenfer.getId();
        }
    }//GEN-LAST:event_enfer_vaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_detalles;
    public javax.swing.JButton Ts_guard;
    private javax.swing.JComboBox<String> enfer_va;
    private com.toedter.calendar.JDateChooser fecha_va;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> medici_va;
    public javax.swing.JButton reporte;
    public javax.swing.JButton ts_cargar;
    public javax.swing.JPanel ts_guar;
    public javax.swing.JPanel ts_guar1;
    public javax.swing.JPanel ts_guar2;
    // End of variables declaration//GEN-END:variables
class fondo extends JPanel {

     Image imag;
    
    @Override
    public void paint(Graphics g){
    
        
        imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();
        
        g.drawImage(imag,0,0,getWidth(),getHeight(),this );
        
        setOpaque(false);
        
        super.paint(g);
    }
    
}
}
