/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import com.formdev.flatlaf.FlatDarculaLaf;
import control.Controller10;
import examples.validar_usuario;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import models.usuario;

/**
 *
 * @author User
 */
public class reset_contraseña extends javax.swing.JFrame {

   int cedula  = 0;
    int xMouse;
    int yMouse;
    public Controller10 controller;
    
    /**
     * Creates new form reset_contraseña
     */
    public reset_contraseña() {
        initComponents();
         this.setLocationRelativeTo(null);
         controller = new Controller10(this);
         try {
        UIManager.setLookAndFeel(new FlatDarculaLaf()); // primero el Look&Feel
    } catch (Exception ex) {
        ex.printStackTrace();
    }
         models.validar_campos.soloNumeros(rc_cedu, jLabel_1confi);
          models.validar_campos.soloLetras(rc_comi, jLabel_2confi);
           models.validar_campos.soloLetras(rc_ani, jLabel_3confi);
             models.validar_campos.soloLetras(rc_color, jLabel_5confi);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cont = new javax.swing.JPanel();
        preguntas_seguridad = new fondo();
        rc_ani = new javax.swing.JTextField();
        rc_comi = new javax.swing.JTextField();
        rc_color = new javax.swing.JTextField();
        cancel = new javax.swing.JPanel();
        jButton_cancel = new javax.swing.JButton();
        confir = new javax.swing.JPanel();
        jButton_confir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rc_cedu = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_1confi = new javax.swing.JLabel();
        jLabel_2confi = new javax.swing.JLabel();
        jLabel_3confi = new javax.swing.JLabel();
        jLabel_4confi = new javax.swing.JLabel();
        jLabel_5confi = new javax.swing.JLabel();
        titulo = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cont.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        preguntas_seguridad.setMinimumSize(new java.awt.Dimension(490, 430));
        preguntas_seguridad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rc_ani.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rc_ani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rc_aniActionPerformed(evt);
            }
        });
        rc_ani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rc_aniKeyTyped(evt);
            }
        });
        preguntas_seguridad.add(rc_ani, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 140, 30));

        rc_comi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rc_comi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rc_comiKeyTyped(evt);
            }
        });
        preguntas_seguridad.add(rc_comi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 140, 30));

        rc_color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rc_colorKeyTyped(evt);
            }
        });
        preguntas_seguridad.add(rc_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 140, 30));

        cancel.setBackground(new java.awt.Color(0, 204, 204));
        cancel.setLayout(new java.awt.CardLayout());

        jButton_cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancel.setText("Cancelar");
        jButton_cancel.setContentAreaFilled(false);
        jButton_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_cancelMouseClicked(evt);
            }
        });
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });
        cancel.add(jButton_cancel, "card2");

        preguntas_seguridad.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 100, 30));

        confir.setBackground(new java.awt.Color(0, 204, 204));
        confir.setLayout(new java.awt.CardLayout());

        jButton_confir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_confir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_confir.setText("Confimar");
        jButton_confir.setContentAreaFilled(false);
        jButton_confir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_confirMouseClicked(evt);
            }
        });
        jButton_confir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirActionPerformed(evt);
            }
        });
        confir.add(jButton_confir, "card2");

        preguntas_seguridad.add(confir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar preguntas de Seguridad");
        preguntas_seguridad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 60));

        rc_cedu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rc_cedu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rc_ceduKeyTyped(evt);
            }
        });
        preguntas_seguridad.add(rc_cedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula:");
        jPanel5.add(jLabel2);

        preguntas_seguridad.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Comida favorita:");
        jPanel6.add(jLabel11);

        preguntas_seguridad.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, 30));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Animal favorito:");
        jPanel7.add(jLabel13);

        preguntas_seguridad.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 130, 30));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Color favorito:");
        jPanel9.add(jLabel14);

        preguntas_seguridad.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 130, 30));
        preguntas_seguridad.add(jLabel_1confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 180, 20));
        preguntas_seguridad.add(jLabel_2confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 190, 20));
        preguntas_seguridad.add(jLabel_3confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 20));
        preguntas_seguridad.add(jLabel_4confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 210, 20));
        preguntas_seguridad.add(jLabel_5confi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, 30));

        cont.add(preguntas_seguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 430));

        jPanel1.add(cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 490, 430));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloMouseDragged(evt);
            }
        });
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, red_squrLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                .addGap(0, 444, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void tituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_tituloMouseDragged

    private void tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_tituloMousePressed
    
    private void jButton_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_cancelMouseClicked

        RVsistemas pm = new RVsistemas();
        pm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton_cancelMouseClicked

    private void jButton_confirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_confirMouseClicked
        
        
       if (rc_cedu.getText().trim().isEmpty() || rc_comi.getText().trim().isEmpty() 
        || rc_ani.getText().trim().isEmpty()
        || rc_color.getText().trim().isEmpty()) {
    
    JOptionPane.showMessageDialog(null, "Campos Vacíos");

    if (rc_cedu.getText().trim().isEmpty()) {
        jLabel_1confi.setText("Campo obligatorio");
        jLabel_1confi.setForeground(Color.orange);
    } else {
        jLabel_1confi.setText("");
    }

    if (rc_comi.getText().trim().isEmpty()) {
        jLabel_2confi.setText("Campo obligatorio");
        jLabel_2confi.setForeground(Color.orange);
    } else {
        jLabel_2confi.setText("");
    }

    if (rc_ani.getText().trim().isEmpty()) {
        jLabel_3confi.setText("Campo obligatorio");
        jLabel_3confi.setForeground(Color.orange);
    } else {
        jLabel_3confi.setText("");
    }

    if (rc_color.getText().trim().isEmpty()) {
        jLabel_5confi.setText("Campo obligatorio");
        jLabel_5confi.setForeground(Color.orange);
    } else {
        jLabel_5confi.setText("");
    }

} else {
    try {
        int cedula = Integer.parseInt(rc_cedu.getText().trim());
        String comi = rc_comi.getText().trim();
        String ani = rc_ani.getText().trim();
        String color = rc_color.getText().trim();

        validar_usuario validandopre = new validar_usuario();
        usuario pre = new usuario();
        pre.setCedula(cedula);
        pre.setComida_favorita(comi);
        pre.setAnimal_favorito(ani);
        pre.setColor_favorito(color);

        usuario pregun = validandopre.obtenerpregunta(pre);

        if (pregun != null) {
            this.rc_cedu.setText("");
            this.rc_comi.setText("");
            this.rc_ani.setText("");
            this.rc_color.setText("");

            cambio_contra m = new cambio_contra(cedula);
            m.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Datos Inválidos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La cédula debe ser un número válido", "Error", JOptionPane.ERROR_MESSAGE);
        jLabel_1confi.setText("Debe ingresar un número");
    }
}
        
       
    }//GEN-LAST:event_jButton_confirMouseClicked

    private void rc_aniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rc_aniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rc_aniActionPerformed

    private void rc_ceduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rc_ceduKeyTyped
         rc_cedu.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (rc_cedu.getText().length() >= 8) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_rc_ceduKeyTyped

    private void rc_comiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rc_comiKeyTyped
        rc_comi.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (rc_comi.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_rc_comiKeyTyped

    private void rc_aniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rc_aniKeyTyped
        rc_ani.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (rc_ani.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_rc_aniKeyTyped

    private void rc_colorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rc_colorKeyTyped
        rc_color.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (rc_color.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_rc_colorKeyTyped

    private void jButton_confirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirActionPerformed
        
    }//GEN-LAST:event_jButton_confirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset_contraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
        UIManager.setLookAndFeel(new FlatDarculaLaf()); // primero el Look&Feel
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset_contraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel cancel;
    public javax.swing.JPanel confir;
    private javax.swing.JPanel cont;
    private javax.swing.JLabel exit;
    public javax.swing.JButton jButton_cancel;
    public javax.swing.JButton jButton_confir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_1confi;
    private javax.swing.JLabel jLabel_2confi;
    private javax.swing.JLabel jLabel_3confi;
    private javax.swing.JLabel jLabel_4confi;
    private javax.swing.JLabel jLabel_5confi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel preguntas_seguridad;
    private javax.swing.JTextField rc_ani;
    private javax.swing.JTextField rc_cedu;
    private javax.swing.JTextField rc_color;
    private javax.swing.JTextField rc_comi;
    private javax.swing.JPanel red_squr;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
class fondo extends JPanel {

     Image imag;
    
    @Override
    public void paint(Graphics g){
    
        
        imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();
        
        g.drawImage(imag,0,0,getWidth(),getHeight(),this );
        
        setOpaque(false);
        
        super.paint(g);
    }
    
}
}
