
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;


import common.conexion;
import control.Controller2;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement; 
import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader; 
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Respal extends javax.swing.JPanel {

    public Controller2 controller;
    /**
     * Creates new form RMerc
     */
    public Respal() {
        initComponents();
        controller = new Controller2(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo();
        jLabel5 = new javax.swing.JLabel();
        rm_mod = new javax.swing.JPanel();
        restauarar_db = new javax.swing.JButton();
        rm_lim = new javax.swing.JPanel();
        busca_res = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Ruta_rp = new javax.swing.JTextField();
        Ruta_rt = new javax.swing.JTextField();
        rm_mod1 = new javax.swing.JPanel();
        respalda = new javax.swing.JButton();
        rm_lim1 = new javax.swing.JPanel();
        busca_pl = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Respaldo y Restauracion de Base de Datos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 760, 50));

        rm_mod.setBackground(new java.awt.Color(0, 204, 204));
        rm_mod.setLayout(new java.awt.CardLayout());

        restauarar_db.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        restauarar_db.setForeground(new java.awt.Color(255, 255, 255));
        restauarar_db.setText("Restaurar");
        restauarar_db.setContentAreaFilled(false);
        restauarar_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restauarar_dbActionPerformed(evt);
            }
        });
        rm_mod.add(restauarar_db, "card2");

        jPanel1.add(rm_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 110, 30));

        rm_lim.setBackground(new java.awt.Color(0, 204, 204));
        rm_lim.setLayout(new java.awt.CardLayout());

        busca_res.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        busca_res.setForeground(new java.awt.Color(255, 255, 255));
        busca_res.setText("Buscar");
        busca_res.setContentAreaFilled(false);
        busca_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_resActionPerformed(evt);
            }
        });
        rm_lim.add(busca_res, "card2");

        jPanel1.add(rm_lim, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 100, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Restauracion");
        jPanel6.add(jLabel3);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, 30));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Respaldo");
        jPanel7.add(jLabel4);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 30));

        Ruta_rp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(Ruta_rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, 30));

        Ruta_rt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(Ruta_rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 190, 30));

        rm_mod1.setBackground(new java.awt.Color(0, 204, 204));
        rm_mod1.setLayout(new java.awt.CardLayout());

        respalda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        respalda.setForeground(new java.awt.Color(255, 255, 255));
        respalda.setText("Respaldar");
        respalda.setContentAreaFilled(false);
        respalda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respaldaActionPerformed(evt);
            }
        });
        rm_mod1.add(respalda, "card2");

        jPanel1.add(rm_mod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 110, 30));

        rm_lim1.setBackground(new java.awt.Color(0, 204, 204));
        rm_lim1.setLayout(new java.awt.CardLayout());

        busca_pl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        busca_pl.setForeground(new java.awt.Color(255, 255, 255));
        busca_pl.setText("Buscar");
        busca_pl.setContentAreaFilled(false);
        busca_pl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busca_plActionPerformed(evt);
            }
        });
        rm_lim1.add(busca_pl, "card2");

        jPanel1.add(rm_lim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 100, 30));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void respaldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respaldaActionPerformed
        String ruta = Ruta_rp.getText();
    if (ruta.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione una ruta de destino.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String user = conexion.getUser();
    String password = conexion.getClave();
    String db = conexion.getDB();
    String mysqldumpPath = "C:\\xampp\\mysql\\bin\\mysqldump.exe";

    try {
        String command = "\"" + mysqldumpPath + "\" -u " + user + " " + db + " -r \"" + ruta + "\"";
        if (!password.isEmpty()) {
            command = "\"" + mysqldumpPath + "\" -u " + user + " -p" + password + " " + db + " -r \"" + ruta + "\"";
        }

        Process proceso = Runtime.getRuntime().exec(command);

        BufferedReader stdInput = new BufferedReader(new InputStreamReader(proceso.getInputStream()));
        BufferedReader stdError = new BufferedReader(new InputStreamReader(proceso.getErrorStream()));

        StringBuilder errores = new StringBuilder();
        String s;
        while ((s = stdError.readLine()) != null) {
            errores.append(s).append("\n");
        }

        if (errores.length() > 0) {
            JOptionPane.showMessageDialog(this, "Error al realizar respaldo:\n" + errores.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int resultado = proceso.waitFor();
        if (resultado == 0) {
            JOptionPane.showMessageDialog(this, "Respaldo realizado exitosamente en:\n" + ruta);
        } else {
            JOptionPane.showMessageDialog(this, "Error desconocido al respaldar la base de datos.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
    }

    }//GEN-LAST:event_respaldaActionPerformed

    private void busca_plActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_plActionPerformed
        // TODO add your handling code here:
           JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar respaldo de base de datos");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int opcion = chooser.showSaveDialog(this);
    if (opcion == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile();
        String ruta = archivo.getAbsolutePath();

    
        if (!ruta.toLowerCase().endsWith(".sql")) {
            ruta += ".sql";
        }

        Ruta_rp.setText(ruta);
    }

    }//GEN-LAST:event_busca_plActionPerformed

    private void restauarar_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restauarar_dbActionPerformed
        // TODO add your handling code here:
        String ruta = Ruta_rt.getText();
    if (ruta.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un archivo .sql para restaurar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String user = conexion.getUser();
    String password = conexion.getClave();
    String db = conexion.getDB();
    String mysqlPath = "C:\\xampp\\mysql\\bin\\mysql.exe";

    try {
        String url = "jdbc:mysql://localhost:3308/";
        try (Connection con = DriverManager.getConnection(url, user, password);
             Statement stmt = con.createStatement()) {
            stmt.executeUpdate("CREATE DATABASE IF NOT EXISTS " + db);
        } catch (SQLException e) {
            conexion.errorManager(e);
            return;
        }

        String rutaComillas = "\"" + ruta + "\"";
        String command = "cmd.exe /c \"" + mysqlPath + " -u " + user
                         + (password.isEmpty() ? "" : " -p" + password)
                         + " " + db + " < " + rutaComillas + "\"";

        System.out.println("Ejecutando comando: " + command);

        Process proceso = Runtime.getRuntime().exec(command);

        BufferedReader stdError = new BufferedReader(new InputStreamReader(proceso.getErrorStream()));
        StringBuilder errores = new StringBuilder();
        String s;
        while ((s = stdError.readLine()) != null) {
            errores.append(s).append("\n");
        }

        int resultado = proceso.waitFor();

        if (resultado == 0 && errores.length() == 0) {
            JOptionPane.showMessageDialog(this, "Restauración completada exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al restaurar la base de datos:\n" + errores.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
    }

    }//GEN-LAST:event_restauarar_dbActionPerformed

    private void busca_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busca_resActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Seleccionar archivo de respaldo (.sql)");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int opcion = chooser.showOpenDialog(this);
    if (opcion == JFileChooser.APPROVE_OPTION) {
        File archivo = chooser.getSelectedFile();
        String ruta = archivo.getAbsolutePath();

        
        if (!ruta.toLowerCase().endsWith(".sql")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un archivo .sql válido", 
                                          "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Ruta_rt.setText(ruta);
    }

    }//GEN-LAST:event_busca_resActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ruta_rp;
    private javax.swing.JTextField Ruta_rt;
    public javax.swing.JButton busca_pl;
    public javax.swing.JButton busca_res;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JButton respalda;
    public javax.swing.JButton restauarar_db;
    public javax.swing.JPanel rm_lim;
    public javax.swing.JPanel rm_lim1;
    public javax.swing.JPanel rm_mod;
    public javax.swing.JPanel rm_mod1;
    // End of variables declaration//GEN-END:variables
class fondo extends JPanel {

     Image imag;
    
    @Override
    public void paint(Graphics g){
    
        
        imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();
        
        g.drawImage(imag,0,0,getWidth(),getHeight(),this );
        
        setOpaque(false);
        
        super.paint(g);
    }
    
}
}
