/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paneles;

import com.formdev.flatlaf.FlatDarculaLaf;
import control.Controller9;
import examples.validar_usuario;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import models.usuario;

/**
 *
 * @author User
 */
public class RVsistemas extends javax.swing.JFrame {

    
    int xMouse;
    int yMouse;
    usuario us;
    int contador = 1;
    int id_usuario = 0, cedula = 0;
    
    public Controller9 controller;
     fondo fond = new fondo();
     
    public RVsistemas() {
        this.setContentPane(fond);
        this.setLocationRelativeTo(null);
        initComponents();
        ojo.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png")));

        controller = new Controller9(this);
        try {
        UIManager.setLookAndFeel(new FlatDarculaLaf()); 
    } catch (Exception ex) {
        ex.printStackTrace();
    }
       models.validar_campos.soloNumeros(ingresar_cedula, jLabel_1login);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new fondo();
        ingresar_cedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ini = new javax.swing.JPanel();
        Inicio = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_2login = new javax.swing.JLabel();
        jLabel_1login = new javax.swing.JLabel();
        ingresar_password = new javax.swing.JPasswordField();
        ojo = new javax.swing.JLabel();
        titulo = new javax.swing.JPanel();
        red_squr = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresar_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresar_cedulaKeyTyped(evt);
            }
        });
        login.add(ingresar_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 129, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio De Sesion");
        login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 309, 48));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Olvidaste La contaseña");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 170, -1));

        ini.setBackground(new java.awt.Color(0, 204, 204));
        ini.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ini.setLayout(new java.awt.CardLayout());

        Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Ingresar");
        Inicio.setContentAreaFilled(false);
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        ini.add(Inicio, "card2");

        login.add(ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 150, 40));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cedula:");
        jPanel5.add(jLabel1);

        login.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 120, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contraseña:");
        jPanel6.add(jLabel2);

        login.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 120, 30));
        login.add(jLabel_2login, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 200, 20));
        login.add(jLabel_1login, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 200, 20));

        ingresar_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ingresar_passwordKeyTyped(evt);
            }
        });
        login.add(ingresar_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 259, 130, 30));

        ojo.setBackground(new java.awt.Color(255, 255, 255));
        ojo.setPreferredSize(new java.awt.Dimension(32, 32));
        ojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojoMouseClicked(evt);
            }
        });
        login.add(ojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 70, 30));

        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 460));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                tituloMouseDragged(evt);
            }
        });
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tituloMousePressed(evt);
            }
        });

        red_squr.setBackground(new java.awt.Color(255, 255, 255));

        exit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(102, 102, 102));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout red_squrLayout = new javax.swing.GroupLayout(red_squr);
        red_squr.setLayout(red_squrLayout);
        red_squrLayout.setHorizontalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );
        red_squrLayout.setVerticalGroup(
            red_squrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, red_squrLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                .addGap(0, 654, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(red_squr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RVsistemas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        reset_contraseña rs = new reset_contraseña();
        rs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel5.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
       setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
       jLabel5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel5MouseExited

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        red_squr.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        red_squr.setBackground(new Color(255,255,255));
        exit.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void tituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMousePressed
         xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_tituloMousePressed

    private void tituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_tituloMouseDragged

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        if (ingresar_cedula.getText().trim().isEmpty() || ingresar_password.getText().trim().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Campos Vacios");
        } else {
            ingresar();
        }
       
    }//GEN-LAST:event_InicioActionPerformed

    private void ingresar_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresar_cedulaKeyTyped
        ingresar_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (ingresar_cedula.getText().length() >= 8) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_ingresar_cedulaKeyTyped

    private void ingresar_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ingresar_passwordKeyTyped
        ingresar_password.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (ingresar_password.getText().length() >= 20) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_ingresar_passwordKeyTyped

    private void ojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoMouseClicked
        // TODO add your handling code here:
         if (ingresar_password.getEchoChar() == (char) 0) {
        ingresar_password.setEchoChar('*'); 
        ojo.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png"))); 
    } else {
        ingresar_password.setEchoChar((char) 0); 
        ojo.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_abierto.png"))); 
    }
    }//GEN-LAST:event_ojoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RVsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RVsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RVsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RVsistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 
        try {
        UIManager.setLookAndFeel(new FlatDarculaLaf());
    } catch (Exception ex) {
        ex.printStackTrace();
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RVsistemas().setVisible(true);
            }
        });
    }
    protected void ingresar(){
      int usuario_cedula = Integer.valueOf(ingresar_cedula.getText());
    String clave = String.valueOf(ingresar_password.getText());
    
    validar_usuario validando = new validar_usuario();
    usuario usua = new usuario();
    usua.setCedula(usuario_cedula);
    usua.setPassword(clave);
    us = validando.obtenerusuario(usua);
    
    if (us != null) {
        contador = 0;
        int rol_usuario = us.getId_rol();
        
        id_usuario = us.getCedula(); 
        Interfaz inter = new Interfaz(rol_usuario);
        
        inter.setVisible(true);
        this.dispose();
        this.ingresar_cedula.setText("");
        this.ingresar_password.setText("");
        
    } else {
        contador++;
        JOptionPane.showConfirmDialog(null, "Datos invalidos, Error");
        if (contador >= 4) {
            JOptionPane.showConfirmDialog(null, "demasiados Intentos por seguridad El Sistema se Cerrara");
            System.exit(0);
        }
    }
        
    }
    protected void cambio_ventana(JPanel ventana_activa){
        login.setVisible(false);
        ini.setVisible(false);
        ventana_activa.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Inicio;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField ingresar_cedula;
    private javax.swing.JPasswordField ingresar_password;
    public javax.swing.JPanel ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_1login;
    private javax.swing.JLabel jLabel_2login;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel login;
    private javax.swing.JLabel ojo;
    private javax.swing.JPanel red_squr;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables

class fondo extends JPanel {

     Image imag;
    
    @Override
    public void paint(Graphics g){
    
        
        imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();
        
        g.drawImage(imag,0,0,getWidth(),getHeight(),this );
        
        setOpaque(false);
        
        super.paint(g);
    }
    
}
}
