/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import control.Controller8;
import control.cargar_combx;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.usuario;
import models.validar_campos;
import paneles.usuarios.Users;
/**
 *
 * @author User
 */
public class Usuario extends javax.swing.JPanel {
    cargar_combx carga = new cargar_combx();
    int idrol = -1;
    public Controller8 controller;
    /**
     * Creates new form RUsuario
     */
    public Usuario() {
        initComponents();
        // UserFrame es para ver la lista de los usuarios y agregar despues algunas otras opciones
        UserFrame = new Users();
        ojo_usua.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png")));
        controller = new Controller8(this);
        carga.consul_usuario(usua_bus);
        validar_campos.soloNumeros(u_cedu, jLabel_1usu);
        validar_campos.soloLetras(u_nomb, jLabel_2usu);
        validar_campos.soloLetras(u_apell, jLabel_3usu);
        validar_campos.soloLetras(u_comi, jLabel_6usu);
        validar_campos.soloLetras(u_ani, jLabel_7usu);
        validar_campos.soloLetras(u_color, jLabel_9usu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondo();
        u_nomb = new javax.swing.JTextField();
        u_cedu = new javax.swing.JTextField();
        u_apell = new javax.swing.JTextField();
        u_ani = new javax.swing.JTextField();
        u_comi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        u_color = new javax.swing.JTextField();
        ru_cance = new javax.swing.JPanel();
        canc_U = new javax.swing.JButton();
        ru_guard = new javax.swing.JPanel();
        guard_U = new javax.swing.JButton();
        ru_lim = new javax.swing.JPanel();
        limp_U = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_1usu = new javax.swing.JLabel();
        jLabel_2usu = new javax.swing.JLabel();
        jLabel_3usu = new javax.swing.JLabel();
        jLabel_4usu = new javax.swing.JLabel();
        jLabel_5usu = new javax.swing.JLabel();
        jLabel_6usu = new javax.swing.JLabel();
        jLabel_7usu = new javax.swing.JLabel();
        jLabel_8usu = new javax.swing.JLabel();
        jLabel_9usu = new javax.swing.JLabel();
        u_cont = new javax.swing.JPasswordField();
        u_conf = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usua_bus = new javax.swing.JComboBox<>();
        ojo_usua = new javax.swing.JLabel();
        bt_list_users = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 560));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        u_nomb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        u_nomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_nombKeyTyped(evt);
            }
        });
        jPanel1.add(u_nomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 130, 30));

        u_cedu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        u_cedu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_ceduKeyTyped(evt);
            }
        });
        jPanel1.add(u_cedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 130, 30));

        u_apell.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        u_apell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_apellKeyTyped(evt);
            }
        });
        jPanel1.add(u_apell, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 130, 30));

        u_ani.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        u_ani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_aniKeyTyped(evt);
            }
        });
        jPanel1.add(u_ani, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 140, 30));

        u_comi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        u_comi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_comiKeyTyped(evt);
            }
        });
        jPanel1.add(u_comi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 140, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 760, 50));

        u_color.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_colorKeyTyped(evt);
            }
        });
        jPanel1.add(u_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 140, 30));

        ru_cance.setBackground(new java.awt.Color(0, 204, 204));
        ru_cance.setLayout(new java.awt.CardLayout());

        canc_U.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        canc_U.setForeground(new java.awt.Color(255, 255, 255));
        canc_U.setText("Cancelar");
        canc_U.setContentAreaFilled(false);
        ru_cance.add(canc_U, "card2");

        jPanel1.add(ru_cance, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 100, 30));

        ru_guard.setBackground(new java.awt.Color(0, 204, 204));
        ru_guard.setLayout(new java.awt.CardLayout());

        guard_U.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        guard_U.setForeground(new java.awt.Color(255, 255, 255));
        guard_U.setText("Guardar");
        guard_U.setContentAreaFilled(false);
        guard_U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guard_UMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guard_UMousePressed(evt);
            }
        });
        guard_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guard_UActionPerformed(evt);
            }
        });
        ru_guard.add(guard_U, "card2");

        jPanel1.add(ru_guard, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 100, 30));

        ru_lim.setBackground(new java.awt.Color(0, 204, 204));
        ru_lim.setLayout(new java.awt.CardLayout());

        limp_U.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limp_U.setForeground(new java.awt.Color(255, 255, 255));
        limp_U.setText("Limpiar");
        limp_U.setContentAreaFilled(false);
        limp_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limp_UActionPerformed(evt);
            }
        });
        ru_lim.add(limp_U, "card2");

        jPanel1.add(ru_lim, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 100, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Comida favorita:");
        jPanel3.add(jLabel7);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");
        jPanel4.add(jLabel3);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel5.add(jLabel2);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 30));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cedula:");
        jPanel6.add(jLabel11);

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, 30));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        jPanel7.add(jLabel4);

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 90, 30));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Animal favorito:");
        jPanel8.add(jLabel9);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 140, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Color favorito:");
        jPanel10.add(jLabel10);

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 140, 30));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirma contraseña:");
        jPanel11.add(jLabel5);

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 160, 30));
        jPanel1.add(jLabel_1usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, 20));
        jPanel1.add(jLabel_2usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 170, 20));
        jPanel1.add(jLabel_3usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 170, 20));
        jPanel1.add(jLabel_4usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 170, 20));
        jPanel1.add(jLabel_5usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 170, 20));
        jPanel1.add(jLabel_6usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 170, 20));
        jPanel1.add(jLabel_7usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 170, 20));
        jPanel1.add(jLabel_8usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 170, 20));
        jPanel1.add(jLabel_9usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 170, 20));

        u_cont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_contKeyTyped(evt);
            }
        });
        jPanel1.add(u_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 130, 30));

        u_conf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                u_confKeyTyped(evt);
            }
        });
        jPanel1.add(u_conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 130, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo:");
        jPanel12.add(jLabel1);

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, 30));

        usua_bus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        usua_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usua_busActionPerformed(evt);
            }
        });
        jPanel1.add(usua_bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 130, 30));

        ojo_usua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojo_usuaMouseClicked(evt);
            }
        });
        jPanel1.add(ojo_usua, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 50, 30));

        bt_list_users.setText("Lista de Usuarios");
        bt_list_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_list_usersActionPerformed(evt);
            }
        });
        jPanel1.add(bt_list_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 130, 40));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void guard_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guard_UActionPerformed
        if (u_cedu.getText().trim().isEmpty() ||
        u_nomb.getText().trim().isEmpty() ||
        u_apell.getText().trim().isEmpty() ||
        u_comi.getText().trim().isEmpty() ||
        u_ani.getText().trim().isEmpty() ||
        u_color.getText().trim().isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "Campos Vacíos");
       validar_campos.validarCampoVacio(u_cedu, jLabel_1usu);
       validar_campos.validarCampoVacio(u_nomb, jLabel_2usu);
       validar_campos.validarCampoVacio(u_apell, jLabel_3usu);
       validar_campos.validarCampoVacio(u_cont, jLabel_4usu);
       validar_campos.validarCampoVacio(u_conf, jLabel_5usu);
       validar_campos.validarCampoVacio(u_comi, jLabel_6usu);
       validar_campos.validarCampoVacio(u_ani, jLabel_7usu);
       validar_campos.validarCampoVacio(u_color, jLabel_9usu);
       
        return;
    }

    boolean valido = validar_campos.validarPasswords(
            u_cont, u_conf, jLabel_4usu, jLabel_5usu);

    if (!valido) {
        return;
    }

    int cedula = Integer.parseInt(u_cedu.getText());
    String nombre = u_nomb.getText();
    String apellido = u_apell.getText();
    String contrasena = new String(u_cont.getPassword());
    String confi_contra = new String(u_conf.getPassword());
    String comida = u_comi.getText();
    String animal = u_ani.getText();
    String color = u_color.getText();

    int preguard = JOptionPane.showConfirmDialog(this, "¿Desea Guardar el Usuario?");
    if (preguard == JOptionPane.YES_OPTION) {
        usuario usu = new usuario();
        usu.setCedula(cedula);
        usu.setNombre(nombre);
        usu.setPassword(contrasena);
        usu.setConfi_password(confi_contra);
        usu.setComida_favorita(comida);
        usu.setAnimal_favorito(animal);
        usu.setColor_favorito(color);
        usu.setId_rol(idrol);
        usu.save();

        JOptionPane.showMessageDialog(this, "Los Datos se Guardaron Correctamente");

        limpiarCampos();
    } else {
        limpiarCampos();
    }
}

private void limpiarCampos() {
    u_cedu.setText("");
    u_nomb.setText("");
    u_apell.setText("");
    u_cont.setText("");
    u_conf.setText("");
    u_comi.setText("");
    u_ani.setText(""); 
    u_color.setText("");
    carga.consul_usuario(usua_bus);
        
    }//GEN-LAST:event_guard_UActionPerformed

    private void guard_UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guard_UMouseClicked
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_guard_UMouseClicked

    private void guard_UMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guard_UMousePressed
        // TODO add your handling code here:   
        
    }//GEN-LAST:event_guard_UMousePressed

    private void limp_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limp_UActionPerformed
        // TODO add your handling code here:
              this.u_cedu.setText("");
              this.u_nomb.setText("");
              this.u_apell.setText("");
              this.u_cont.setText("");
              this.u_conf.setText("");
              this.u_comi.setText("");
              this.u_ani.setText(""); 
              this.u_color.setText("");
    }//GEN-LAST:event_limp_UActionPerformed

    private void u_ceduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_ceduKeyTyped
        u_cedu.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_cedu.getText().length() >= 8) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_ceduKeyTyped

    private void u_nombKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_nombKeyTyped
       u_nomb.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_nomb.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_nombKeyTyped

    private void u_apellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_apellKeyTyped
        u_apell.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_apell.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_apellKeyTyped

    private void u_contKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_contKeyTyped
        u_cont.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_cont.getText().length() >= 20) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_contKeyTyped

    private void u_confKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_confKeyTyped
        u_conf.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_conf.getText().length() >= 20) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_confKeyTyped

    private void u_comiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_comiKeyTyped
        u_comi.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_comi.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_comiKeyTyped

    private void u_aniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_aniKeyTyped
        u_ani.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_ani.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_aniKeyTyped

    private void u_colorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u_colorKeyTyped
        u_color.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				if (u_color.getText().length() >= 15) {
					e.consume();
				}
			}
		});
    }//GEN-LAST:event_u_colorKeyTyped

    private void usua_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usua_busActionPerformed
        // TODO add your handling code here:
        Object usuaseleccionado = usua_bus.getSelectedItem();
        if (usuaseleccionado instanceof String) {
           String rol = (String) usuaseleccionado;
}else if (usuaseleccionado instanceof models.rol) {
            models.rol selectedrol = (models.rol)usuaseleccionado;
            idrol = selectedrol.getId();
        }
    }//GEN-LAST:event_usua_busActionPerformed

    private void ojo_usuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo_usuaMouseClicked
        // TODO add your handling code here:
           if (u_cont.getEchoChar() == (char) 0|| u_conf.getEchoChar()== (char) 0) {
        u_cont.setEchoChar('*'); 
        u_conf.setEchoChar('*'); 
        ojo_usua.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_cerrado.png"))); 
    } else {
        u_cont.setEchoChar((char) 0); 
        u_conf.setEchoChar((char) 0);
        ojo_usua.setIcon(new ImageIcon(getClass().getResource("/imagen/ojo_abierto.png"))); 
    }
    }//GEN-LAST:event_ojo_usuaMouseClicked

    private void bt_list_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_list_usersActionPerformed
        UserFrame.setVisible(true);
    }//GEN-LAST:event_bt_list_usersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_list_users;
    public javax.swing.JButton canc_U;
    public javax.swing.JButton guard_U;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_1usu;
    private javax.swing.JLabel jLabel_2usu;
    private javax.swing.JLabel jLabel_3usu;
    private javax.swing.JLabel jLabel_4usu;
    private javax.swing.JLabel jLabel_5usu;
    private javax.swing.JLabel jLabel_6usu;
    private javax.swing.JLabel jLabel_7usu;
    private javax.swing.JLabel jLabel_8usu;
    private javax.swing.JLabel jLabel_9usu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JButton limp_U;
    private javax.swing.JLabel ojo_usua;
    public javax.swing.JPanel ru_cance;
    public javax.swing.JPanel ru_guard;
    public javax.swing.JPanel ru_lim;
    private javax.swing.JTextField u_ani;
    private javax.swing.JTextField u_apell;
    private javax.swing.JTextField u_cedu;
    private javax.swing.JTextField u_color;
    private javax.swing.JTextField u_comi;
    private javax.swing.JPasswordField u_conf;
    private javax.swing.JPasswordField u_cont;
    private javax.swing.JTextField u_nomb;
    private javax.swing.JComboBox<String> usua_bus;
    // End of variables declaration//GEN-END:variables
    private Users UserFrame;
    
    class fondo extends JPanel {
    

     Image imag;
    
    @Override
    public void paint(Graphics g){
    
        
        imag = new ImageIcon(getClass().getResource("/imagen/fondo1.png")).getImage();
        
        g.drawImage(imag,0,0,getWidth(),getHeight(),this );
        
        setOpaque(false);
        
        super.paint(g);
    }
    
}
}
